config/routes.rb
Rails.application.routes.draw do
  
  get 'live/:live_id', :to => 'frontend#live', as: "live" # pg: needs to be out of unauthenticated block
  
  # clip API
  namespace :api do
    get 'clips/', to: "clip#index"
    get 'clip/:id', to: "clip#show"
    post 'clip', to: "clip#create"
    patch 'clip/:id', to: "clip#update", as: :clip_update
    get 'events', to: "event#index"
    get 'event/:live_id', to: "event#show", as: :event_show
    get 'event/clips/:live_id', to: "event#clips", as: :event_clips
    get 'creators', to: "creator#index"
  end

  unauthenticated do
    root :to => "pages#index", as: :unauthenticated_root
    resources :creators, only: [:show]
  end
  
  devise_for :creators, path: '',
              path_names: { sign_in: 'login', sign_out: 'logout',
                            password: 'secret',
                            unlock: 'unlock', registration: 'register'} ,
               controllers: { registrations: 'creators/registrations',
                             sessions: 'creators/sessions',
                             confirmations: 'confirmations'
                           }
                            
  authenticated :creator  do
    root :to => "creators#show" , as: :authenticated_root
    
    resources :creators,  only: [:show, :edit]
    resources :dashboard

    get 'event/show/:id', to: "event#show", as: :event_show
    get 'event/new', to: "event#new", as: :event_new
    post 'event/create', to: "event#create", as: :event_create
    patch 'event/update', to: "event#update", as: :event_update
  end

  resources :links
  get '/:id' => 'creators#show', as: :social_url
    

end

app/views/pages/index.html.erb
<div class="login-box">
  <div style=" margin-bottom: 10px">
    <img src="<%= asset_path('logo/logo-with-text.png') %>" width="300px"/>
  </div>
  <h1>Decentralized Live Streaming Platform</h1>
  <p class="subtitle-color">
    Start a live stream and allow you audience to mint NFTs of the best moments!
  </p>
  <p>
    <%= link_to "Sign Up", new_creator_registration_path, class: "" %> |
    <%= link_to "Log In", new_creator_session_path, class: "" %>

  </p>
</div>