config/routes.rb
Rails.application.routes.draw do
  
  get 'live/:live_id', :to => 'frontend#live', as: "live" # pg: needs to be out of unauthenticated block
  
  # clip API
  namespace :api do
    get 'clips/', to: "clip#index"
    get 'clip/:id', to: "clip#show"
    post 'clip', to: "clip#create"
    patch 'clip/:id', to: "clip#update", as: :clip_update
    get 'events', to: "event#index"
    get 'event/:live_id', to: "event#show", as: :event_show
    get 'event/clips/:live_id', to: "event#clips", as: :event_clips
    get 'creators', to: "creator#index"
  end

  unauthenticated do
    root :to => "pages#index", as: :unauthenticated_root
    resources :creators, only: [:show]
  end
  
  devise_for :creators, path: '',
              path_names: { sign_in: 'login', sign_out: 'logout',
                            password: 'secret',
                            unlock: 'unlock', registration: 'register'} ,
               controllers: { registrations: 'creators/registrations',
                             sessions: 'creators/sessions',
                             confirmations: 'confirmations'
                           }
                            
  authenticated :creator  do
    root :to => "creators#show" , as: :authenticated_root
    
    resources :creators,  only: [:show, :edit]
    resources :dashboard

    get 'event/show/:id', to: "event#show", as: :event_show
    get 'event/new', to: "event#new", as: :event_new
    post 'event/create', to: "event#create", as: :event_create
    patch 'event/update', to: "event#update", as: :event_update
  end

  resources :links
  get '/:id' => 'creators#show', as: :social_url
    

end

app/models/event.rb
require 'securerandom'
class Event < ApplicationRecord
    acts_as_taggable_on :tags
    
    default_scope { order(created_at: :desc)}
    
    belongs_to :creator
    has_many :clip

    validates :live_id, presence: true, uniqueness: true
    validates :name, presence: true
    validates :stream_url, presence: true
    


    after_initialize :default_values

    def default_values
        self.live_id ||= SecureRandom.alphanumeric(12)
    end


end

app/controllers/api/event_controller.rb
class Api::EventController < Api::AuthController
  before_action :event_is_present

  def index
    events = Event.all
    render json: events, status: 200
  end

  # GET api/event/:live_id
  def show
    render json: current_event, status: 200
  end

  # GET api/event/clips/:live_id
  def clips
    render json: current_event.clip.order(id: :desc), :methods => [:service_url, :relative_url, :rarible_url], status: 200
  end

  private

  def event_is_present
    render status: :unauthorized, json: { error: "live_id is missing." } unless current_event.present?
  end

  def custom_stream_url
    params[:stream_url]
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_creator!

  def show
    @event = Event.find_by(id: params[:id], creator: current_creator)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create!(
        creator: current_creator,
        name: permitted_params[:name],
        stream_url: permitted_params[:stream_url]
    )
    redirect_to '/'
  end

  def update
    @event = Event.find(param_id)
    @event.update!(permitted_params)
    redirect_to event_show_path(@event.id)
  end

  private

  def param_id
    params[:event][:id]
  end

  def permitted_params
    params.require(:event).permit(:name, :stream_url, :tag_list)
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/new.html.erb
<%= render 'shared/header' %>
<div class="cp-wrap">

  <div class="cp-card">
    <%= form_for @event, :url => { :action => "create" }, remote: false do |f| %>
      <label>Name</label>
      <%= f.text_field :name %>
      <br/>
      <br/>
      <label>Livepeer URL</label>
      <%= f.text_field :stream_url %>
      <br/>
      <br/>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>


  <div>
    <%= link_to 'Back', authenticated_root_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/event/show.html.erb
<%= render 'shared/header' %>
<div class="cp-wrap">
  <div class="cp-card" style="text-align: center">
    <h1>Event: <%= @event.name %></h1>
  </div>

  <div class="cp-card">
    <div style="display: flex; justify-content: space-between; align-items: center">
      <div>Live ID: <span class="subtitle-color" style="font-weight: bold; font-variant: all-small-caps;"><%= @event.live_id %></span></div>
      <div>
        <a href="/live/<%= @event.live_id %>" target="_blank" class="btn btn-primary">
          <strong>
            View
          </strong>
        </a>
      </div>
    </div>
    <hr/>
    <div>
      <%= form_for @event, :url => { :action => "update" }, remote: false do |f| %>
        <%= f.hidden_field :id, :value => @event.id %>
        <label>Livepeer URL</label>
        <%= f.text_field :stream_url, value: @event.stream_url %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="cp-small-light-text">
      Expected URL format: https://cdn.livepeer.com/hls/274ecn88f1pocum0/index.m3u8
    </div>
  </div>


  <div>
    <%= link_to 'Back', authenticated_root_path, class: "btn btn-primary" %>
  </div>
</div>